<div class="entry-edit" id="iceimport-dashboard" style="display:none">
    <div class="entry-edit-head"><h4>
            <?php echo $this->__('ICEImport Statistic') ?></h4>
        <a href="<?php print $this->getManageUrl(); ?>"
           style="float: right;"><?php echo $this->helper('iceimport')->__('Edit'); ?>
        </a>
    </div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="iceImportStatistic_table">
                <thead>
                <tr class="headings">
                    <th class="no-link"><span>Name</span></th>
                    <th class="no-link"><span></span>Value</span></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getStatistics() as $key => $value): ?>
                    <tr class="<?php echo ++$key % 2 ? '' : 'even' ?> ">
                        <td><?php echo $value['label']; ?></td>
                        <td><?php echo $value['value']; ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td><?php echo $this->getProfiles('Import All Products'); ?></td>
                    <td><?php echo $this->getLayout()->createBlock('adminhtml/widget_button')->setType('button')
                            ->setClass('save')->setLabel($this->__('Run Profile in Popup'))
                            ->setOnClick('startProfile()')
                            ->toHtml(); ?>
                        <a href="#" style="float: right;"
                           onclick="editProfile();"><?php echo $this->helper('iceimport')->__('Edit'); ?>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>

<script type="text/javascript">
    //run profile import/export
    function startProfile() {
        var profile = jQuery("#ice_export_profiles option:selected").attr('value');
        if (profile != undefined || profile != null) {
            var url = '<?php echo $this->getUrl('/system_convert_gui/run', array('id'=>'{profile_id}')) ?>';
            var run_url = url.replace("{profile_id}", profile);
            window.open(run_url);
        } else {
            alert("Can not run process");
        }
    }
    //edit import/export profile
    function editProfile() {
        var profile = jQuery("#ice_export_profiles option:selected").attr('value');
        if (profile != undefined || profile != null) {
            var url = '<?php echo $this->getUrl('/system_convert_gui/edit', array('id'=>'{profile_id}')) ?>';
            var run_url = url.replace("{profile_id}", profile);
            window.open(run_url);
        } else {
            alert("Can not run process");
        }
    }
</script>