<?php $_problems = $this->getIceimportProblemsDigest() ?>
<?php
$is_allowed = false;
try {
    $is_allowed = $this->isAllowed();
} catch ( Exception $e ) {
}
?>
<?php if ( $is_allowed == true ) : ?>
    <?php if ( ! empty( $_problems ) && is_array( $_problems ) && count( $_problems ) > 0 ): ?>
        <div class="notification-global" id="iceimport-warning">
        <span class="f-right">
            <a href="<?php print $this->getManageUrl(); ?>"
               title="<?php echo $this->helper( 'iceimport' )->__( 'Open in new window' ); ?>"><?php echo $this->helper( 'iceimport' )->__( 'Go to system check section' ); ?></a>
        </span>
            <strong class="label"><?php echo $this->helper( 'iceimport' )->__( 'Warning' ); ?></strong>
            <?php echo $this->helper( 'iceimport' )->__( "The Iceimport extensions doesn't work properly, please go to configuration page and check the problems." ); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>